name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
          import-path: github.com/nlanatta/simple-rest-api

      - name: Install format check tool
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

      - name: Run format check
        run: golangci-lint run ./...

      - name: Build
        run: go build -mod=vendor

      - name: Run tests
        run: go test -v ./...
